// <auto-generated />
using System;
using MealBuilder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealBuilder.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809140154_SeedBuiltInIngredients")]
    partial class SeedBuiltInIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MealBuilder.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriesPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("CarbohydratesPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("FatPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("FiberPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("SaltPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("SourceCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("SugarsPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Ingredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ingredients_CaloriesPer100g", "CaloriesPer100g BETWEEN 0 AND 900");

                            t.HasCheckConstraint("CK_Ingredients_Name", "length(trim(Name)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Ingredients_NutrientsPer100g", "ProteinPer100g BETWEEN 0 AND 100 AND FatPer100g BETWEEN 0 AND 100 AND CarbohydratesPer100g BETWEEN 0 AND 100 AND SugarsPer100g BETWEEN 0 AND 100 AND FiberPer100g BETWEEN 0 AND 100 AND SaltPer100g BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Ingredients_Ownership", "(OwnerId IS NULL AND SourceName IS NOT NULL AND SourceCode IS NOT NULL AND SourceVersion IS NOT NULL) OR (OwnerId IS NOT NULL AND SourceName IS NULL AND SourceCode IS NULL AND SourceVersion IS NULL)");

                            t.HasCheckConstraint("CK_Ingredients_Sugars", "SugarsPer100g <= CarbohydratesPer100g");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPer100g = 109.0,
                            CarbohydratesPer100g = 0.0,
                            FatPer100g = 1.8100000000000001,
                            FiberPer100g = 0.0,
                            Name = "Chicken breast fillet, raw",
                            ProteinPer100g = 23.25,
                            SaltPer100g = 0.128,
                            SourceCode = "V416100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 224.0,
                            CarbohydratesPer100g = 0.0,
                            FatPer100g = 16.390000000000001,
                            FiberPer100g = 0.0,
                            Name = "Ground beef, raw",
                            ProteinPer100g = 19.102,
                            SaltPer100g = 0.14499999999999999,
                            SourceCode = "U010100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 180.0,
                            CarbohydratesPer100g = 0.0,
                            FatPer100g = 11.199999999999999,
                            FiberPer100g = 0.0,
                            Name = "Salmon, deep-frozen",
                            ProteinPer100g = 19.899999999999999,
                            SaltPer100g = 0.079799999999999996,
                            SourceCode = "T410200",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPer100g = 135.0,
                            CarbohydratesPer100g = 0.34000000000000002,
                            FatPer100g = 9.0,
                            FiberPer100g = 0.0,
                            Name = "Egg, raw",
                            ProteinPer100g = 13.175000000000001,
                            SaltPer100g = 0.38500000000000001,
                            SourceCode = "E111100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.34000000000000002
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPer100g = 62.0,
                            CarbohydratesPer100g = 4.0300000000000002,
                            FatPer100g = 3.4900000000000002,
                            FiberPer100g = 0.0,
                            Name = "Whole milk, fresh, 3.5% fat",
                            ProteinPer100g = 3.5499999999999998,
                            SaltPer100g = 0.0872,
                            SourceCode = "M111300",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 4.0300000000000002
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 67.0,
                            CarbohydratesPer100g = 4.1299999999999999,
                            FatPer100g = 3.46,
                            FiberPer100g = 0.0,
                            Name = "Natural yogurt, 3.5% fat",
                            ProteinPer100g = 3.98,
                            SaltPer100g = 0.10000000000000001,
                            SourceCode = "M141300",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 4.1299999999999999
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 66.0,
                            CarbohydratesPer100g = 3.6800000000000002,
                            FatPer100g = 0.17999999999999999,
                            FiberPer100g = 0.0,
                            Name = "Quark, low-fat",
                            ProteinPer100g = 11.85,
                            SaltPer100g = 0.084000000000000005,
                            SourceCode = "M713100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 3.6800000000000002
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 351.0,
                            CarbohydratesPer100g = 77.099999999999994,
                            FatPer100g = 0.62,
                            FiberPer100g = 2.5,
                            Name = "White rice, raw",
                            ProteinPer100g = 7.931,
                            SaltPer100g = 0.039419999999999997,
                            SourceCode = "C352000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.28000000000000003
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPer100g = 348.0,
                            CarbohydratesPer100g = 53.299999999999997,
                            FatPer100g = 6.6500000000000004,
                            FiberPer100g = 10.983000000000001,
                            Name = "Oat flakes",
                            ProteinPer100g = 13.220000000000001,
                            SaltPer100g = 0.0049500000000000004,
                            SourceCode = "C133000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.73999999999999999
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPer100g = 346.0,
                            CarbohydratesPer100g = 68.832999999999998,
                            FatPer100g = 1.6000000000000001,
                            FiberPer100g = 3.4060000000000001,
                            Name = "Pasta, egg-free, raw",
                            ProteinPer100g = 12.4,
                            SaltPer100g = 0.0077999999999999996,
                            SourceCode = "E401000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 2.0150000000000001
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPer100g = 272.0,
                            CarbohydratesPer100g = 50.539999999999999,
                            FatPer100g = 2.9700000000000002,
                            FiberPer100g = 4.0,
                            Name = "Wheat bread",
                            ProteinPer100g = 8.6899999999999995,
                            SaltPer100g = 1.4205000000000001,
                            SourceCode = "B311000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 3.9700000000000002
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPer100g = 83.0,
                            CarbohydratesPer100g = 17.899999999999999,
                            FatPer100g = 0.10000000000000001,
                            FiberPer100g = 1.4199999999999999,
                            Name = "Potato, peeled, raw",
                            ProteinPer100g = 1.9399999999999999,
                            SaltPer100g = 0.0085000000000000006,
                            SourceCode = "K110100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = 13,
                            CaloriesPer100g = 348.0,
                            CarbohydratesPer100g = 71.769999999999996,
                            FatPer100g = 0.93000000000000005,
                            FiberPer100g = 5.2999999999999998,
                            Name = "Wheat flour, Type 405",
                            ProteinPer100g = 10.460000000000001,
                            SaltPer100g = 0.0022000000000000001,
                            SourceCode = "C214100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.30701000000000001
                        },
                        new
                        {
                            Id = 14,
                            CaloriesPer100g = 323.0,
                            CarbohydratesPer100g = 44.799999999999997,
                            FatPer100g = 1.7,
                            FiberPer100g = 17.600000000000001,
                            Name = "Lentils, mature",
                            ProteinPer100g = 23.356999999999999,
                            SaltPer100g = 0.017999999999999999,
                            SourceCode = "H725100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 1.3
                        },
                        new
                        {
                            Id = 15,
                            CaloriesPer100g = 899.0,
                            CarbohydratesPer100g = 0.0,
                            FatPer100g = 99.900000000000006,
                            FiberPer100g = 0.0,
                            Name = "Olive oil",
                            ProteinPer100g = 0.0,
                            SaltPer100g = 0.0037200000000000002,
                            SourceCode = "Q120000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.0
                        },
                        new
                        {
                            Id = 16,
                            CaloriesPer100g = 747.0,
                            CarbohydratesPer100g = 0.57099999999999995,
                            FatPer100g = 82.200000000000003,
                            FiberPer100g = 0.0,
                            Name = "Butter",
                            ProteinPer100g = 1.1879999999999999,
                            SaltPer100g = 0.028000000000000001,
                            SourceCode = "Q611000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.57099999999999995
                        },
                        new
                        {
                            Id = 17,
                            CaloriesPer100g = 22.0,
                            CarbohydratesPer100g = 3.25,
                            FatPer100g = 0.11,
                            FiberPer100g = 1.3,
                            Name = "Tomato, raw",
                            ProteinPer100g = 0.94999999999999996,
                            SaltPer100g = 0.01,
                            SourceCode = "G561100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 3.25
                        },
                        new
                        {
                            Id = 18,
                            CaloriesPer100g = 34.0,
                            CarbohydratesPer100g = 6.0099999999999998,
                            FatPer100g = 0.14999999999999999,
                            FiberPer100g = 1.3999999999999999,
                            Name = "Onion, raw",
                            ProteinPer100g = 1.1559999999999999,
                            SaltPer100g = 0.021999999999999999,
                            SourceCode = "G480100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 6.0099999999999998
                        },
                        new
                        {
                            Id = 19,
                            CaloriesPer100g = 58.0,
                            CarbohydratesPer100g = 11.699999999999999,
                            FatPer100g = 0.5,
                            FiberPer100g = 2.2749999999999999,
                            Name = "Apple, raw",
                            ProteinPer100g = 0.42399999999999999,
                            SaltPer100g = 0.002,
                            SourceCode = "F110100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 10.487
                        },
                        new
                        {
                            Id = 20,
                            CaloriesPer100g = 79.0,
                            CarbohydratesPer100g = 15.890000000000001,
                            FatPer100g = 0.40000000000000002,
                            FiberPer100g = 2.0,
                            Name = "Banana, raw",
                            ProteinPer100g = 1.319,
                            SaltPer100g = 0.0012999999999999999,
                            SourceCode = "F503100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 13.890000000000001
                        });
                });

            modelBuilder.Entity("MealBuilder.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MealBuilder.Domain.Ingredients.Ingredient", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
