// <auto-generated />
using System;
using MealBuilder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealBuilder.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819163158_AddMealPlanning")]
    partial class AddMealPlanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MealBuilder.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriesPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("CarbohydratesPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("FatPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("FiberPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("SaltPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("SourceCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("SugarsPer100g")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Ingredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ingredients_CaloriesPer100g", "CaloriesPer100g BETWEEN 0 AND 900");

                            t.HasCheckConstraint("CK_Ingredients_Name", "length(trim(Name)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Ingredients_NutrientsPer100g", "ProteinPer100g BETWEEN 0 AND 100 AND FatPer100g BETWEEN 0 AND 100 AND CarbohydratesPer100g BETWEEN 0 AND 100 AND SugarsPer100g BETWEEN 0 AND 100 AND FiberPer100g BETWEEN 0 AND 100 AND SaltPer100g BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Ingredients_Ownership", "(OwnerId IS NULL AND SourceName IS NOT NULL AND SourceCode IS NOT NULL AND SourceVersion IS NOT NULL) OR (OwnerId IS NOT NULL AND SourceName IS NULL AND SourceCode IS NULL AND SourceVersion IS NULL)");

                            t.HasCheckConstraint("CK_Ingredients_Sugars", "SugarsPer100g <= CarbohydratesPer100g");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPer100g = 109.0,
                            CarbohydratesPer100g = 0.0,
                            FatPer100g = 1.8100000000000001,
                            FiberPer100g = 0.0,
                            Name = "Chicken breast fillet, raw",
                            ProteinPer100g = 23.25,
                            SaltPer100g = 0.128,
                            SourceCode = "V416100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 224.0,
                            CarbohydratesPer100g = 0.0,
                            FatPer100g = 16.390000000000001,
                            FiberPer100g = 0.0,
                            Name = "Ground beef, raw",
                            ProteinPer100g = 19.102,
                            SaltPer100g = 0.14499999999999999,
                            SourceCode = "U010100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 180.0,
                            CarbohydratesPer100g = 0.0,
                            FatPer100g = 11.199999999999999,
                            FiberPer100g = 0.0,
                            Name = "Salmon, deep-frozen",
                            ProteinPer100g = 19.899999999999999,
                            SaltPer100g = 0.079799999999999996,
                            SourceCode = "T410200",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPer100g = 135.0,
                            CarbohydratesPer100g = 0.34000000000000002,
                            FatPer100g = 9.0,
                            FiberPer100g = 0.0,
                            Name = "Egg, raw",
                            ProteinPer100g = 13.175000000000001,
                            SaltPer100g = 0.38500000000000001,
                            SourceCode = "E111100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.34000000000000002
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPer100g = 62.0,
                            CarbohydratesPer100g = 4.0300000000000002,
                            FatPer100g = 3.4900000000000002,
                            FiberPer100g = 0.0,
                            Name = "Whole milk, fresh, 3.5% fat",
                            ProteinPer100g = 3.5499999999999998,
                            SaltPer100g = 0.0872,
                            SourceCode = "M111300",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 4.0300000000000002
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 67.0,
                            CarbohydratesPer100g = 4.1299999999999999,
                            FatPer100g = 3.46,
                            FiberPer100g = 0.0,
                            Name = "Natural yogurt, 3.5% fat",
                            ProteinPer100g = 3.98,
                            SaltPer100g = 0.10000000000000001,
                            SourceCode = "M141300",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 4.1299999999999999
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 66.0,
                            CarbohydratesPer100g = 3.6800000000000002,
                            FatPer100g = 0.17999999999999999,
                            FiberPer100g = 0.0,
                            Name = "Quark, low-fat",
                            ProteinPer100g = 11.85,
                            SaltPer100g = 0.084000000000000005,
                            SourceCode = "M713100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 3.6800000000000002
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 351.0,
                            CarbohydratesPer100g = 77.099999999999994,
                            FatPer100g = 0.62,
                            FiberPer100g = 2.5,
                            Name = "White rice, raw",
                            ProteinPer100g = 7.931,
                            SaltPer100g = 0.039419999999999997,
                            SourceCode = "C352000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.28000000000000003
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPer100g = 348.0,
                            CarbohydratesPer100g = 53.299999999999997,
                            FatPer100g = 6.6500000000000004,
                            FiberPer100g = 10.983000000000001,
                            Name = "Oat flakes",
                            ProteinPer100g = 13.220000000000001,
                            SaltPer100g = 0.0049500000000000004,
                            SourceCode = "C133000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.73999999999999999
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPer100g = 346.0,
                            CarbohydratesPer100g = 68.832999999999998,
                            FatPer100g = 1.6000000000000001,
                            FiberPer100g = 3.4060000000000001,
                            Name = "Pasta, egg-free, raw",
                            ProteinPer100g = 12.4,
                            SaltPer100g = 0.0077999999999999996,
                            SourceCode = "E401000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 2.0150000000000001
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPer100g = 272.0,
                            CarbohydratesPer100g = 50.539999999999999,
                            FatPer100g = 2.9700000000000002,
                            FiberPer100g = 4.0,
                            Name = "Wheat bread",
                            ProteinPer100g = 8.6899999999999995,
                            SaltPer100g = 1.4205000000000001,
                            SourceCode = "B311000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 3.9700000000000002
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPer100g = 83.0,
                            CarbohydratesPer100g = 17.899999999999999,
                            FatPer100g = 0.10000000000000001,
                            FiberPer100g = 1.4199999999999999,
                            Name = "Potato, peeled, raw",
                            ProteinPer100g = 1.9399999999999999,
                            SaltPer100g = 0.0085000000000000006,
                            SourceCode = "K110100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = 13,
                            CaloriesPer100g = 348.0,
                            CarbohydratesPer100g = 71.769999999999996,
                            FatPer100g = 0.93000000000000005,
                            FiberPer100g = 5.2999999999999998,
                            Name = "Wheat flour, Type 405",
                            ProteinPer100g = 10.460000000000001,
                            SaltPer100g = 0.0022000000000000001,
                            SourceCode = "C214100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.30701000000000001
                        },
                        new
                        {
                            Id = 14,
                            CaloriesPer100g = 323.0,
                            CarbohydratesPer100g = 44.799999999999997,
                            FatPer100g = 1.7,
                            FiberPer100g = 17.600000000000001,
                            Name = "Lentils, mature",
                            ProteinPer100g = 23.356999999999999,
                            SaltPer100g = 0.017999999999999999,
                            SourceCode = "H725100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 1.3
                        },
                        new
                        {
                            Id = 15,
                            CaloriesPer100g = 899.0,
                            CarbohydratesPer100g = 0.0,
                            FatPer100g = 99.900000000000006,
                            FiberPer100g = 0.0,
                            Name = "Olive oil",
                            ProteinPer100g = 0.0,
                            SaltPer100g = 0.0037200000000000002,
                            SourceCode = "Q120000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.0
                        },
                        new
                        {
                            Id = 16,
                            CaloriesPer100g = 747.0,
                            CarbohydratesPer100g = 0.57099999999999995,
                            FatPer100g = 82.200000000000003,
                            FiberPer100g = 0.0,
                            Name = "Butter",
                            ProteinPer100g = 1.1879999999999999,
                            SaltPer100g = 0.028000000000000001,
                            SourceCode = "Q611000",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 0.57099999999999995
                        },
                        new
                        {
                            Id = 17,
                            CaloriesPer100g = 22.0,
                            CarbohydratesPer100g = 3.25,
                            FatPer100g = 0.11,
                            FiberPer100g = 1.3,
                            Name = "Tomato, raw",
                            ProteinPer100g = 0.94999999999999996,
                            SaltPer100g = 0.01,
                            SourceCode = "G561100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 3.25
                        },
                        new
                        {
                            Id = 18,
                            CaloriesPer100g = 34.0,
                            CarbohydratesPer100g = 6.0099999999999998,
                            FatPer100g = 0.14999999999999999,
                            FiberPer100g = 1.3999999999999999,
                            Name = "Onion, raw",
                            ProteinPer100g = 1.1559999999999999,
                            SaltPer100g = 0.021999999999999999,
                            SourceCode = "G480100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 6.0099999999999998
                        },
                        new
                        {
                            Id = 19,
                            CaloriesPer100g = 58.0,
                            CarbohydratesPer100g = 11.699999999999999,
                            FatPer100g = 0.5,
                            FiberPer100g = 2.2749999999999999,
                            Name = "Apple, raw",
                            ProteinPer100g = 0.42399999999999999,
                            SaltPer100g = 0.002,
                            SourceCode = "F110100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 10.487
                        },
                        new
                        {
                            Id = 20,
                            CaloriesPer100g = 79.0,
                            CarbohydratesPer100g = 15.890000000000001,
                            FatPer100g = 0.40000000000000002,
                            FiberPer100g = 2.0,
                            Name = "Banana, raw",
                            ProteinPer100g = 1.319,
                            SaltPer100g = 0.0012999999999999999,
                            SourceCode = "F503100",
                            SourceName = "Bundeslebensmittelschlüssel (BLS)",
                            SourceVersion = "4.0",
                            SugarsPer100g = 13.890000000000001
                        });
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.DailyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeInWeeklySummary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Date")
                        .IsUnique();

                    b.ToTable("DailyPlans", (string)null);
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.DailyPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Grams")
                        .HasColumnType("REAL");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("PlannedTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Portions")
                        .HasColumnType("REAL");

                    b.Property<int?>("PreparedRecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("PreparedRecipeId");

                    b.HasIndex("DailyPlanId", "PlannedTime", "Id");

                    b.ToTable("DailyPlanItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyPlanItems_Grams", "Grams IS NULL OR (Grams > 0 AND Grams <= 100000)");

                            t.HasCheckConstraint("CK_DailyPlanItems_ItemType", "ItemType IN (1, 2)");

                            t.HasCheckConstraint("CK_DailyPlanItems_Portions", "Portions IS NULL OR (Portions > 0 AND Portions = ROUND(Portions, 2))");

                            t.HasCheckConstraint("CK_DailyPlanItems_SourceAndQuantity", "(ItemType = 1 AND IngredientId IS NOT NULL AND PreparedRecipeId IS NULL AND Grams IS NOT NULL AND Portions IS NULL) OR (ItemType = 2 AND IngredientId IS NULL AND PreparedRecipeId IS NOT NULL AND Grams IS NULL AND Portions IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.PreparedRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PreparedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalPortions")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SourceRecipeId");

                    b.HasIndex("OwnerId", "NameSnapshot");

                    b.HasIndex("OwnerId", "PreparedDate");

                    b.ToTable("PreparedRecipes", null, t =>
                        {
                            t.HasCheckConstraint("CK_PreparedRecipes_NameSnapshot", "length(trim(NameSnapshot)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_PreparedRecipes_TotalPortions", "TotalPortions > 0");
                        });
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.PreparedRecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Calories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Carbohydrates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Fat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Fiber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Grams")
                        .HasColumnType("REAL");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreparedRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Protein")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Salt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Sugars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("PreparedRecipeId", "Position")
                        .IsUnique();

                    b.ToTable("PreparedRecipeIngredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_PreparedRecipeIngredients_Grams", "Grams > 0 AND Grams <= 100000");

                            t.HasCheckConstraint("CK_PreparedRecipeIngredients_NameSnapshot", "length(trim(NameSnapshot)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_PreparedRecipeIngredients_Nutrition", "Calories >= 0 AND Protein >= 0 AND Fat >= 0 AND Carbohydrates >= 0 AND Sugars >= 0 AND Fiber >= 0 AND Salt >= 0");

                            t.HasCheckConstraint("CK_PreparedRecipeIngredients_Position", "Position > 0");

                            t.HasCheckConstraint("CK_PreparedRecipeIngredients_Sugars", "Sugars <= Carbohydrates");
                        });
                });

            modelBuilder.Entity("MealBuilder.Domain.Profiles.UserNutritionProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActivityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyCalorieTarget")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<int?>("SexForCalculation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeightGoal")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("UserId");

                    b.ToTable("UserNutritionProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserNutritionProfiles_ActivityLevel", "ActivityLevel IS NULL OR ActivityLevel IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_UserNutritionProfiles_CalculationInputs", "(BirthDate IS NULL AND SexForCalculation IS NULL AND HeightCm IS NULL AND WeightKg IS NULL AND ActivityLevel IS NULL AND WeightGoal IS NULL) OR (BirthDate IS NOT NULL AND SexForCalculation IS NOT NULL AND HeightCm IS NOT NULL AND WeightKg IS NOT NULL AND ActivityLevel IS NOT NULL AND WeightGoal IS NOT NULL)");

                            t.HasCheckConstraint("CK_UserNutritionProfiles_DailyCalorieTarget", "DailyCalorieTarget BETWEEN 1000 AND 10000");

                            t.HasCheckConstraint("CK_UserNutritionProfiles_HeightCm", "HeightCm IS NULL OR HeightCm BETWEEN 100 AND 250");

                            t.HasCheckConstraint("CK_UserNutritionProfiles_SexForCalculation", "SexForCalculation IS NULL OR SexForCalculation IN (1, 2)");

                            t.HasCheckConstraint("CK_UserNutritionProfiles_WeightGoal", "WeightGoal IS NULL OR WeightGoal IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_UserNutritionProfiles_WeightKg", "WeightKg IS NULL OR WeightKg BETWEEN 30 AND 400");
                        });
                });

            modelBuilder.Entity("MealBuilder.Domain.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Recipes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Recipes_Name", "length(trim(Name)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Recipes_Servings", "Servings BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("MealBuilder.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Grams")
                        .HasColumnType("REAL");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId", "IngredientId")
                        .IsUnique();

                    b.HasIndex("RecipeId", "Position");

                    b.ToTable("RecipeIngredients", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecipeIngredients_Grams", "Grams > 0 AND Grams <= 100000");

                            t.HasCheckConstraint("CK_RecipeIngredients_Position", "Position > 0");
                        });
                });

            modelBuilder.Entity("MealBuilder.Domain.Recipes.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Position");

                    b.ToTable("RecipeSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecipeSteps_Instruction", "length(trim(Instruction)) BETWEEN 1 AND 2000");

                            t.HasCheckConstraint("CK_RecipeSteps_Position", "Position > 0");
                        });
                });

            modelBuilder.Entity("MealBuilder.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MealBuilder.Domain.Ingredients.Ingredient", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.DailyPlan", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.DailyPlanItem", b =>
                {
                    b.HasOne("MealBuilder.Domain.MealPlanning.DailyPlan", null)
                        .WithMany("Items")
                        .HasForeignKey("DailyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealBuilder.Domain.Ingredients.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealBuilder.Domain.MealPlanning.PreparedRecipe", "PreparedRecipe")
                        .WithMany()
                        .HasForeignKey("PreparedRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ingredient");

                    b.Navigation("PreparedRecipe");
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.PreparedRecipe", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealBuilder.Domain.Recipes.Recipe", "SourceRecipe")
                        .WithMany()
                        .HasForeignKey("SourceRecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceRecipe");
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.PreparedRecipeIngredient", b =>
                {
                    b.HasOne("MealBuilder.Domain.MealPlanning.PreparedRecipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("PreparedRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealBuilder.Domain.Profiles.UserNutritionProfile", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("MealBuilder.Domain.Profiles.UserNutritionProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealBuilder.Domain.Recipes.Recipe", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MealBuilder.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("MealBuilder.Domain.Ingredients.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealBuilder.Domain.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealBuilder.Domain.Recipes.RecipeStep", b =>
                {
                    b.HasOne("MealBuilder.Domain.Recipes.Recipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MealBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.DailyPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealBuilder.Domain.MealPlanning.PreparedRecipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MealBuilder.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
