// <auto-generated />
using System;
using MealBuilder.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealBuilder.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606094726_AddPreparedBatchSnapshots")]
    partial class AddPreparedBatchSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MealBuilder.Web.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FiberPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GramsPerMilliliter")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GramsPerPiece")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaltPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SugarPer100g")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Grams")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreparedRecipeBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ServingsCount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MenuId");

                    b.HasIndex("PreparedRecipeBatchId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.PreparedRecipeBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CookedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCaloriesSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFiberSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalProteinSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSaltSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalServings")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSugarSnapshot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("PreparedRecipeBatches");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.RecipeComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Grams")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentRecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentRecipeId");

                    b.HasIndex("ParentRecipeId", "ComponentRecipeId")
                        .IsUnique();

                    b.ToTable("RecipeComponents");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Grams")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.MenuItem", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.Ingredient", "Ingredient")
                        .WithMany("MenuItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealBuilder.Web.Models.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealBuilder.Web.Models.PreparedRecipeBatch", "PreparedRecipeBatch")
                        .WithMany("MenuItems")
                        .HasForeignKey("PreparedRecipeBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealBuilder.Web.Models.Recipe", "Recipe")
                        .WithMany("MenuItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ingredient");

                    b.Navigation("Menu");

                    b.Navigation("PreparedRecipeBatch");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.PreparedRecipeBatch", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.Recipe", "Recipe")
                        .WithMany("PreparedRecipeBatches")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.RecipeComponent", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.Recipe", "ComponentRecipe")
                        .WithMany("UsedAsComponentInRecipes")
                        .HasForeignKey("ComponentRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealBuilder.Web.Models.Recipe", "ParentRecipe")
                        .WithMany("Components")
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponentRecipe");

                    b.Navigation("ParentRecipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.RecipeIngredient", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealBuilder.Web.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Ingredient", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Menu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.PreparedRecipeBatch", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Recipe", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("MenuItems");

                    b.Navigation("PreparedRecipeBatches");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("UsedAsComponentInRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
