// <auto-generated />
using System;
using MealBuilder.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealBuilder.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630190313_RenameMenusToDailyPlans")]
    partial class RenameMenusToDailyPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MealBuilder.Web.Models.DailyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyPlans");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.DailyPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Grams")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreparedRecipeBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ServingsCount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyPlanId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("PreparedRecipeBatchId");

                    b.HasIndex("RecipeId");

                    b.ToTable("DailyPlanItems");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FiberPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GramsPerMilliliter")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GramsPerPiece")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaltPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SugarPer100g")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.PreparedRecipeBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CookedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalServings")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("PreparedRecipeBatches");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.PreparedRecipeBatchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CaloriesSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FiberSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Grams")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreparedRecipeBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProteinSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaltSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SugarSnapshot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreparedRecipeBatchId");

                    b.HasIndex("SourceIngredientId");

                    b.HasIndex("SourceRecipeId");

                    b.ToTable("PreparedRecipeBatchItems");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPlannedDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultServingsPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FinalWeightGrams")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.RecipeComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Grams")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentRecipeId");

                    b.HasIndex("ParentRecipeId", "ComponentRecipeId")
                        .IsUnique();

                    b.ToTable("RecipeComponents");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Grams")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.DailyPlanItem", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.DailyPlan", "DailyPlan")
                        .WithMany("DailyPlanItems")
                        .HasForeignKey("DailyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealBuilder.Web.Models.Ingredient", "Ingredient")
                        .WithMany("DailyPlanItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealBuilder.Web.Models.PreparedRecipeBatch", "PreparedRecipeBatch")
                        .WithMany("DailyPlanItems")
                        .HasForeignKey("PreparedRecipeBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealBuilder.Web.Models.Recipe", "Recipe")
                        .WithMany("DailyPlanItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyPlan");

                    b.Navigation("Ingredient");

                    b.Navigation("PreparedRecipeBatch");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.PreparedRecipeBatch", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.Recipe", "Recipe")
                        .WithMany("PreparedRecipeBatches")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.PreparedRecipeBatchItem", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.PreparedRecipeBatch", "PreparedRecipeBatch")
                        .WithMany("Items")
                        .HasForeignKey("PreparedRecipeBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealBuilder.Web.Models.Ingredient", "SourceIngredient")
                        .WithMany()
                        .HasForeignKey("SourceIngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealBuilder.Web.Models.Recipe", "SourceRecipe")
                        .WithMany()
                        .HasForeignKey("SourceRecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PreparedRecipeBatch");

                    b.Navigation("SourceIngredient");

                    b.Navigation("SourceRecipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.RecipeComponent", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.Recipe", "ComponentRecipe")
                        .WithMany("UsedAsComponentInRecipes")
                        .HasForeignKey("ComponentRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealBuilder.Web.Models.Recipe", "ParentRecipe")
                        .WithMany("Components")
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponentRecipe");

                    b.Navigation("ParentRecipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.RecipeIngredient", b =>
                {
                    b.HasOne("MealBuilder.Web.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealBuilder.Web.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.DailyPlan", b =>
                {
                    b.Navigation("DailyPlanItems");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Ingredient", b =>
                {
                    b.Navigation("DailyPlanItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.PreparedRecipeBatch", b =>
                {
                    b.Navigation("DailyPlanItems");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealBuilder.Web.Models.Recipe", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("DailyPlanItems");

                    b.Navigation("PreparedRecipeBatches");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("UsedAsComponentInRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
